name:  morning pipeline for Playwright Tests
on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM every day
  push:
    branches: 
    - 'master'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test-to-run:
        description: 'add your npx code here'
        required: false
        default: 'npm run script:to:run'
        type: string
      workers:
        description: 'number of workers to use'
        required: false
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
      browsers:
        description: 'browsers to run tests on' 
        required: false
        default: 'chromium' 
        type: choice
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    # Add cache for Playwright browsers
    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        # Cache key based on OS, Playwright version from package-lock.json and selected browser
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}-${{ github.event.inputs.browsers || 'chromium' }}
        
    # Install browsers only if cache miss
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps ${{ github.event.inputs.browsers || 'chromium' }}

    - name: Run Playwright tests
      env:
        test-to-run: ${{ github.event.inputs.test-to-run  || 'npm run script:to:run'}}
        workers: ${{ github.event.inputs.workers || '1' }}
        browsers: ${{ github.event.inputs.browsers || 'chromium' }}
      run: |
        ${{env.test-to-run}} --workers=${{env.workers}} --project=${{env.browsers}} || npm run posttest  
        
    - name: upload allure report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-playwright-report
        path: allure-report/
        retention-days: 30

    - name: upload allure report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-tests-report
        path: test-results/
        retention-days: 30


